// Auto-generated by ai_trainer3.js
// Expert AI parameters — after 130 total experiments across 3 training rounds
// Final model: v122_pipeline_harvest_combo
// Round 1 adoptions: 7/30  |  Round 2: see improvements.md  |  Round 3: 8/50

export const EXPERT_PARAMS = {
  "VP_WEIGHT": 25,
  "LP_VP_WEIGHT": 6,
  "LP_DIRECT": 0.8,
  "RING_BONUS": [
    10,
    7,
    3,
    1
  ],
  "TREE_VALUE": {
    "seed": 0.4,
    "tree-small": 2,
    "tree-medium": 4.5,
    "tree-large": 10
  },
  "LP_FUTURE_WEIGHTS": [
    0,
    7,
    3,
    1.8,
    1,
    0.5
  ],
  "OPP_BOARD_FACTOR": 0.9,
  "AREA_CENTER_BONUS": 5,
  "AREA_RING1_BONUS": 2.5,
  "AREA_OPP_FACTOR": 0.7,
  "opponentLargePenalty": 0,
  "opponentMediumPenalty": 0,
  "harvestUrgencyBonus": 0,
  "mediumNearCenterBonus": 0,
  "lpConversionBonus": 0,
  "endgameRevolution": 99,
  "endgameVPBoost": 0
};
